### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by lizidev** [luoxiaozero/leptos-devtools#1]
## Roadmap

- [ ] Developer Tools displays the leptos component arrangement. eg: For.
   - [ ] For
   - [ ] Route
   - [ ] Suspense
- [ ] tracing component props.
   - [x] static prop
   - [ ] reactive prop
- [ ] tracing component DOM.
